// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetControllers():Promise<Array<main.Interop_GenericController>>;

export function LastRawEvent():Promise<main.Interop_RawEvent>;

export function OnFrontendReady():Promise<void>;

export function SaveCalibration(arg1:main.Interop_ControllerCalibration):Promise<void>;

export function SubscribeRaw(arg1:string):Promise<void>;

export function UnsubscribeRaw():Promise<void>;
