// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {profile_runner} from '../models';

export function ClearProfile():Promise<void>;

export function GetControllerConfiguration(arg1:string):Promise<main.Interop_ControllerConfiguration>;

export function GetControllers():Promise<Array<main.Interop_GenericController>>;

export function GetLastInstalledModVersion():Promise<string>;

export function GetLatestReleaseVersion():Promise<string>;

export function GetProfiles():Promise<Array<main.Interop_Profile>>;

export function GetSelectedProfile():Promise<string>;

export function GetSyncControlState():Promise<Array<profile_runner.SyncController_ControlState>>;

export function GetVersion():Promise<string>;

export function HasNewerVersion():Promise<boolean>;

export function InstallTrainSimWorldMod():Promise<void>;

export function LastRawEvent():Promise<main.Interop_RawEvent>;

export function LoadConfiguration():Promise<void>;

export function OpenConfigDirectory():Promise<void>;

export function OpenProfileBuilder(arg1:string):Promise<void>;

export function SaveCalibration(arg1:main.Interop_ControllerCalibration):Promise<void>;

export function SelectProfile(arg1:string):Promise<void>;

export function SetLastInstalledModVersion(arg1:string):Promise<void>;

export function SubscribeRaw(arg1:string):Promise<void>;

export function UnsubscribeRaw():Promise<void>;

export function UpdateApp():Promise<boolean>;
