// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProfile() {
  return window['go']['main']['App']['ClearProfile']();
}

export function GetControllers() {
  return window['go']['main']['App']['GetControllers']();
}

export function GetLastInstalledModVersion() {
  return window['go']['main']['App']['GetLastInstalledModVersion']();
}

export function GetLatestReleaseVersion() {
  return window['go']['main']['App']['GetLatestReleaseVersion']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSelectedProfile() {
  return window['go']['main']['App']['GetSelectedProfile']();
}

export function GetSyncControlState() {
  return window['go']['main']['App']['GetSyncControlState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasNewerVersion() {
  return window['go']['main']['App']['HasNewerVersion']();
}

export function InstallTrainSimWorldMod() {
  return window['go']['main']['App']['InstallTrainSimWorldMod']();
}

export function LastRawEvent() {
  return window['go']['main']['App']['LastRawEvent']();
}

export function LoadConfiguration() {
  return window['go']['main']['App']['LoadConfiguration']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function SaveCalibration(arg1) {
  return window['go']['main']['App']['SaveCalibration'](arg1);
}

export function SelectProfile(arg1) {
  return window['go']['main']['App']['SelectProfile'](arg1);
}

export function SetLastInstalledModVersion(arg1) {
  return window['go']['main']['App']['SetLastInstalledModVersion'](arg1);
}

export function SubscribeRaw(arg1) {
  return window['go']['main']['App']['SubscribeRaw'](arg1);
}

export function UnsubscribeRaw() {
  return window['go']['main']['App']['UnsubscribeRaw']();
}

export function UpateApp() {
  return window['go']['main']['App']['UpateApp']();
}

export function UpdateApp() {
  return window['go']['main']['App']['UpdateApp']();
}
