// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetControllers() {
  return window['go']['main']['App']['GetControllers']();
}

export function LastRawEvent() {
  return window['go']['main']['App']['LastRawEvent']();
}

export function OnFrontendReady() {
  return window['go']['main']['App']['OnFrontendReady']();
}

export function SaveCalibration(arg1) {
  return window['go']['main']['App']['SaveCalibration'](arg1);
}

export function SubscribeRaw(arg1) {
  return window['go']['main']['App']['SubscribeRaw'](arg1);
}

export function UnsubscribeRaw() {
  return window['go']['main']['App']['UnsubscribeRaw']();
}
